<div style="background:#FFFFCC;">
<b>MECHANICS</b><br/>
      <strong><em>Grammar</em></strong><br/>
	  <% if strPagename="Gq1" then %> 
	  	<span class="whitelink">Question 1<% if not Session("Gq1") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
        <a href="./Gq1.asp">Question 1</a><% if not Session("Gq1") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq2" then %> 
	  	<span class="whitelink">Question 2<% if not Session("Gq2") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq2.asp">Question 2</a><% if not Session("Gq2") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq3" then %> 
	  	<span class="whitelink">Question 3<% if not Session("Gq3") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq3.asp">Question 3</a><% if not Session("Gq3") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq4" then %>
	    <span class="whitelink">Question 4<% if not Session("Gq4") = "" then %> &#8730;<% end if %></span><br>
	  <% else %> 
	    <a href="./Gq4.asp">Question 4</a><% if not Session("Gq4") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq5" then %> 
	     <span class="whitelink">Question 5<% if not Session("Gq5") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq5.asp">Question 5</a><% if not Session("Gq5") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq6" then %> 
	  	<span class="whitelink">Question 6<% if not Session("Gq6") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq6.asp">Question 6</a><% if not Session("Gq6") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
  
      <% if strPagename="Gq7" then %> 
	    <span class="whitelink">Question 7<% if not Session("Gq7") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq7.asp">Question 7</a><% if not Session("Gq7") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq8" then %> 
	    <span class="whitelink">Question 8<% if not Session("Gq8") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq8.asp">Question 8</a><% if not Session("Gq8") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq9" then %> 
	     <span class="whitelink">Question 9<% if not Session("Gq9") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq9.asp">Question 9</a><% if not Session("Gq9") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
      <% if strPagename="Gq10" then %> 
	     <span class="whitelink">Question 10<% if not Session("Gq10") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Gq10.asp">Question 10</a><% if not Session("Gq10") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
	  <div class="menubox">
	  <% if strPagename="GqResults" then %> 
		<span class="whitelink">(Results)</span><br>
	  <% else %>
		<a href="./GqResults.asp">(Results)</a><br>	
      <% end if %>
	  </div><br/>
        
		<strong><em>Punctuation</em></strong><br/>
		<% if strPagename="Pq1" then %> 
			<span class="whitelink">Question 1<% if not Session("Pq1") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq1.asp">Question 1</a><% if not Session("Pq1") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq2" then %> 
			<span class="whitelink">Question 2<% if not Session("Pq2") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq2.asp">Question 2</a><% if not Session("Pq2") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq3" then %> 
			<span class="whitelink">Question 3<% if not Session("Pq3") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq3.asp">Question 3</a><% if not Session("Pq3") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq4" then %> 
			<span class="whitelink">Question 4<% if not Session("Pq4") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq4.asp">Question 4</a><% if not Session("Pq4") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq5" then %> 
			<span class="whitelink">Question 5<% if not Session("Pq5") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq5.asp">Question 5</a><% if not Session("Pq5") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq6" then %> 
			<span class="whitelink">Question 6<% if not Session("Pq6") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq6.asp">Question 6</a><% if not Session("Pq6") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq7" then %> 
			<span class="whitelink">Question 7<% if not Session("Pq7") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq7.asp">Question 7</a><% if not Session("Pq7") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq8" then %> 
			<span class="whitelink">Question 8<% if not Session("Pq8") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq8.asp">Question 8</a><% if not Session("Pq8") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq9" then %> 
			<span class="whitelink">Question 9<% if not Session("Pq9") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq9.asp">Question 9</a><% if not Session("Pq9") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		<% if strPagename="Pq10" then %> 
			<span class="whitelink">Question 10<% if not Session("Pq10") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Pq10.asp">Question 10</a><% if not Session("Pq10") = "" then %> &#8730;<% end if %><br>
		<% end if %>
		
		 <div class="menubox">
		<% if strPagename="PqResults" then %> 
			<span class="whitelink">(Results)</span><br>
		<% else %>
        	<a href="./PqResults.asp">(Results)</a><br>
		<% end if %>
		</div><br>
		
         <strong><em>Passive Voice</em></strong><br/>
        <% if strPagename="Vq1" then %> 
			<span class="whitelink">Question 1<% if not Session("Vq1") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Vq1.asp">Question 1</a><% if not Session("Vq1") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		 <% if strPagename="Vq2" then %> 
			<span class="whitelink">Question 2<% if not Session("Vq2") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Vq2.asp">Question 2</a><% if not Session("Vq2") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		 <% if strPagename="Vq3" then %> 
			<span class="whitelink">Question 3<% if not Session("Vq3") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Vq3.asp">Question 3</a><% if not Session("Vq3") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		 <% if strPagename="Vq4" then %> 
			<span class="whitelink">Question 4<% if not Session("Vq4") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Vq4.asp">Question 4</a><% if not Session("Vq4") = "" then %> &#8730;<% end if %><br>
		<% end if %>
        
		 <% if strPagename="Vq5" then %> 
			<span class="whitelink">Question 5<% if not Session("Vq5") = "" then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./Vq5.asp">Question 5</a><% if not Session("Vq5") = "" then %> &#8730;<% end if %><br>
		<% end if %>
		
		<div class="menubox">
		<% if strPagename="VqResults" then %> 
			<span class="whitelink">(Results)</span><br>
		<% else %>
        	<a href="./VqResults.asp">(Results)</a><br>
		<% end if %>
		</div>
		
         <% if strPagename="VqRewrite" then %> 
			<span class="whitelink">Rewrite<% if Session("VqRewriteRate") >=0  then %> &#8730;<% end if %></span><br>
		<% else %>
        	<a href="./VqRewrite.asp">Rewrite</a><% if Session("VqRewriteRate") >=0  then %> &#8730;<% end if %><br>
		<% end if %><br>
	  
		<b>THE WRITING PROCESS </b><br/>
		
      <% if strPagename="Wordy1" then %> 
	     <span class="whitelink">Question 1<% if Session("Wordy1Rate") >=0  then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Wordy1.asp">Question 1</a><% if Session("Wordy1Rate") >=0  then %> &#8730;<% end if %><br>
	  <% end if %>
	  
	   <% if strPagename="Wordy2" then %> 
	     <span class="whitelink">Question 2<% if not Session("Wordiness2") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Wordy2.asp">Question 2</a><% if not Session("Wordiness2") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
	   <% if strPagename="Wordy3" then %> 
	     <span class="whitelink">Question 3<% if not Session("Wordiness3") = "" then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Wordy3.asp">Question 3</a><% if not Session("Wordiness3") = "" then %> &#8730;<% end if %><br>
	  <% end if %>
	  
			
      <% if strPagename="Wordy4" then %> 
	     <span class="whitelink">Question 4<% if Session("Wordy4Rate") >=0  then %> &#8730;<% end if %></span><br><br>
	  <% else %>
	    <a href="./Wordy4.asp">Question 4</a><% if Session("Wordy4Rate") >=0  then %> &#8730;<% end if %><br><br>
	  <% end if %>
	  
		<b>EFFECTIVE WRITING PRINCIPLES</b><br/>
		<% if strPagename="Long1" then %> 
	     <span class="whitelink">Exercise 1<% if Session("Long1Rate") >=0  then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Long1.asp">Exercise 1</a><% if Session("Long1Rate")  >=0  then %> &#8730;<% end if %><br>
	  <% end if %>
	 	
      <% if strPagename="Long2" then %> 
	     <span class="whitelink">Exercise 2<% if Session("Long2Rate") >=0  then %> &#8730;<% end if %></span><br>
	  <% else %>
	    <a href="./Long2.asp">Exercise 2</a><% if Session("Long2Rate") >=0 then %> &#8730;<% end if %><br>
	  <% end if %>
		
		 <% if strPagename="Long3" then %> 
	     <span class="whitelink">Exercise 3<% if Session("Long3Rate") >=0 then %> &#8730;<% end if %></span><br><br>
	  <% else %>
	    <a href="./Long3.asp">Exercise 3</a><% if Session("Long3Rate") >=0 then %> &#8730;<% end if %><br><br>
	  <% end if %>
<br>
	  
</div>
        